# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleupdown',
            name='acticle_bool',
            field=models.BooleanField(default=False, verbose_name='是否赞'),
        ),
    ]
